version: "3.7"
 
services:
  db:
    image: postgres:12.1-alpine
    container_name: postgre12.1
    ports: 
      - 5432:5432
    volumes:
      - ./init.d:/docker-entrypoint-initdb.d
      - postgres12.1:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cucumber
      POSTGRES_PASSWORD: Password12
      PGPASSWORD: Password12
      POSTGRES_DB: CucumberIntelligence
      DATABASE_HOST: localhost
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"  
    hostname: cucumberDB
    restart: always
    user: root

  console:
    image: dpage/pgadmin4:4.17
    container_name: pgadmin4
    ports:
      - 8000:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: cucumber
      PGADMIN_DEFAULT_PASSWORD: Password12
    hostname: cucumberCL
    depends_on:
      - db
    restart: always
volumes:
  postgres12.1:
  pgadmin4: